[toolchain]
anchor_version = "0.32.2"
solana_version = "2.3.0"
[features]
resolution = true
skip-lint = false
[programs.localnet]
pactlance = "9T95KC5YSQ7LV2KwUcY7SyBu6cYF6Urv8fXd7kYaWNpL"
[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
[scripts]
test = "cargo test --workspace"

[programs.devnet]
pactlance = "9T95KC5YSQ7LV2KwUcY7SyBu6cYF6Urv8fXd7kYaWNpL"
